spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_base?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password: "" # 密码
    database: 0
    timeout: 200
# api文档相关配置，生产关闭
springfox:
  documentation:
    enabled: false
file:
  templates-path: "" # 模版文件路径
authorization:
  jwt-secret: ""