server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
    basedir: ../temp # 临时目录，由于Linux系统机制，应用启动创建的临时目录在一段时间未使用时会被删除掉，再次使用则会报错
  servlet:
    context-path: /api # 全局上下文路径
spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: dev-base
# mybatis-plus 配置
mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: auto